-- |
-- Copyright   : (c) Mark Dain 2018
-- License     : MIT
-- Maintainer  : mark@markdain.net
--
-- Utilities for working with the [North American Numbering
-- Plan](https://en.wikipedia.org/wiki/North_American_Numbering_Plan).
module Telephony.PSTN.E164.NANP(
  isUSCA,
  isUSCA_
) where

import Data.Either   (Either(Left, Right))
import Data.Function (($))
import Data.List     (drop, take)
import Data.Maybe    (Maybe(Nothing, Just), isNothing, fromJust)
import Data.String   (String)

import Telephony.PSTN.E164.Types (Country, Prefix,
  Purpose(TollFree, PremiumRate))

isUSCA :: String -> Maybe (Either Country Purpose)
isUSCA "205" = Just $ Left "US" -- Alabama, US
isUSCA "251" = Just $ Left "US" -- Alabama, US
isUSCA "256" = Just $ Left "US" -- Alabama, US
isUSCA "334" = Just $ Left "US" -- Alabama, US
isUSCA "938" = Just $ Left "US" -- Alabama, US
-- +1 907 is assigned to Alaska, US but can also be used by less people in
-- British Columbia. https://en.wikipedia.org/wiki/Area_code_907
isUSCA "907" = Just $ Left "US" -- Alaska, US (also used in British Columbia, CA)
isUSCA "480" = Just $ Left "US" -- Arizona, US
isUSCA "520" = Just $ Left "US" -- Arizona, US
isUSCA "602" = Just $ Left "US" -- Arizona, US
isUSCA "623" = Just $ Left "US" -- Arizona, US
isUSCA "928" = Just $ Left "US" -- Arizona, US
isUSCA "327" = Just $ Left "US" -- Arkansas, US
isUSCA "479" = Just $ Left "US" -- Arkansas, US
isUSCA "501" = Just $ Left "US" -- Arkansas, US
isUSCA "870" = Just $ Left "US" -- Arkansas, US
isUSCA "209" = Just $ Left "US" -- California, US
isUSCA "213" = Just $ Left "US" -- California, US
isUSCA "279" = Just $ Left "US" -- California, US
isUSCA "310" = Just $ Left "US" -- California, US
isUSCA "323" = Just $ Left "US" -- California, US
isUSCA "341" = Just $ Left "US" -- California, US
isUSCA "408" = Just $ Left "US" -- California, US
isUSCA "415" = Just $ Left "US" -- California, US
isUSCA "424" = Just $ Left "US" -- California, US
isUSCA "442" = Just $ Left "US" -- California, US
isUSCA "510" = Just $ Left "US" -- California, US
isUSCA "530" = Just $ Left "US" -- California, US
isUSCA "559" = Just $ Left "US" -- California, US
isUSCA "562" = Just $ Left "US" -- California, US
isUSCA "619" = Just $ Left "US" -- California, US
isUSCA "626" = Just $ Left "US" -- California, US
isUSCA "628" = Just $ Left "US" -- California, US
isUSCA "650" = Just $ Left "US" -- California, US
isUSCA "657" = Just $ Left "US" -- California, US
isUSCA "661" = Just $ Left "US" -- California, US
isUSCA "669" = Just $ Left "US" -- California, US
isUSCA "707" = Just $ Left "US" -- California, US
isUSCA "714" = Just $ Left "US" -- California, US
isUSCA "747" = Just $ Left "US" -- California, US
isUSCA "760" = Just $ Left "US" -- California, US
isUSCA "805" = Just $ Left "US" -- California, US
isUSCA "818" = Just $ Left "US" -- California, US
isUSCA "820" = Just $ Left "US" -- California, US
isUSCA "831" = Just $ Left "US" -- California, US
isUSCA "858" = Just $ Left "US" -- California, US
isUSCA "909" = Just $ Left "US" -- California, US
isUSCA "916" = Just $ Left "US" -- California, US
isUSCA "925" = Just $ Left "US" -- California, US
isUSCA "949" = Just $ Left "US" -- California, US
isUSCA "951" = Just $ Left "US" -- California, US
isUSCA "303" = Just $ Left "US" -- Colorado, US
isUSCA "719" = Just $ Left "US" -- Colorado, US
isUSCA "720" = Just $ Left "US" -- Colorado, US
isUSCA "970" = Just $ Left "US" -- Colorado, US
isUSCA "203" = Just $ Left "US" -- Connecticut, US
isUSCA "475" = Just $ Left "US" -- Connecticut, US
isUSCA "860" = Just $ Left "US" -- Connecticut, US
isUSCA "959" = Just $ Left "US" -- Connecticut, US
isUSCA "302" = Just $ Left "US" -- Delaware, US
isUSCA "202" = Just $ Left "US" -- District of Columbia, US
isUSCA "239" = Just $ Left "US" -- Florida, US
isUSCA "305" = Just $ Left "US" -- Florida, US
isUSCA "321" = Just $ Left "US" -- Florida, US
isUSCA "352" = Just $ Left "US" -- Florida, US
isUSCA "386" = Just $ Left "US" -- Florida, US
isUSCA "407" = Just $ Left "US" -- Florida, US
isUSCA "561" = Just $ Left "US" -- Florida, US
isUSCA "689" = Just $ Left "US" -- Florida, US
isUSCA "727" = Just $ Left "US" -- Florida, US
isUSCA "754" = Just $ Left "US" -- Florida, US
isUSCA "772" = Just $ Left "US" -- Florida, US
isUSCA "786" = Just $ Left "US" -- Florida, US
isUSCA "813" = Just $ Left "US" -- Florida, US
isUSCA "850" = Just $ Left "US" -- Florida, US
isUSCA "863" = Just $ Left "US" -- Florida, US
isUSCA "904" = Just $ Left "US" -- Florida, US
isUSCA "941" = Just $ Left "US" -- Florida, US
isUSCA "954" = Just $ Left "US" -- Florida, US
isUSCA "229" = Just $ Left "US" -- Georgia, US
isUSCA "404" = Just $ Left "US" -- Georgia, US
isUSCA "470" = Just $ Left "US" -- Georgia, US
isUSCA "478" = Just $ Left "US" -- Georgia, US
isUSCA "678" = Just $ Left "US" -- Georgia, US
isUSCA "706" = Just $ Left "US" -- Georgia, US
isUSCA "762" = Just $ Left "US" -- Georgia, US
isUSCA "770" = Just $ Left "US" -- Georgia, US
isUSCA "912" = Just $ Left "US" -- Georgia, US
isUSCA "808" = Just $ Left "US" -- Hawaii, US
isUSCA "208" = Just $ Left "US" -- Idaho, US
isUSCA "986" = Just $ Left "US" -- Idaho, US
isUSCA "217" = Just $ Left "US" -- Illinois, US
isUSCA "224" = Just $ Left "US" -- Illinois, US
isUSCA "309" = Just $ Left "US" -- Illinois, US
isUSCA "312" = Just $ Left "US" -- Illinois, US
isUSCA "331" = Just $ Left "US" -- Illinois, US
isUSCA "447" = Just $ Left "US" -- Illinois, US
isUSCA "464" = Just $ Left "US" -- Illinois, US
isUSCA "618" = Just $ Left "US" -- Illinois, US
isUSCA "630" = Just $ Left "US" -- Illinois, US
isUSCA "708" = Just $ Left "US" -- Illinois, US
isUSCA "730" = Just $ Left "US" -- Illinois, US
isUSCA "773" = Just $ Left "US" -- Illinois, US
isUSCA "779" = Just $ Left "US" -- Illinois, US
isUSCA "815" = Just $ Left "US" -- Illinois, US
isUSCA "847" = Just $ Left "US" -- Illinois, US
isUSCA "872" = Just $ Left "US" -- Illinois, US
isUSCA "219" = Just $ Left "US" -- Indiana, US
isUSCA "260" = Just $ Left "US" -- Indiana, US
isUSCA "317" = Just $ Left "US" -- Indiana, US
isUSCA "463" = Just $ Left "US" -- Indiana, US
isUSCA "574" = Just $ Left "US" -- Indiana, US
isUSCA "765" = Just $ Left "US" -- Indiana, US
isUSCA "812" = Just $ Left "US" -- Indiana, US
isUSCA "930" = Just $ Left "US" -- Indiana, US
isUSCA "319" = Just $ Left "US" -- Iowa, US
isUSCA "515" = Just $ Left "US" -- Iowa, US
isUSCA "563" = Just $ Left "US" -- Iowa, US
isUSCA "641" = Just $ Left "US" -- Iowa, US
isUSCA "712" = Just $ Left "US" -- Iowa, US
isUSCA "316" = Just $ Left "US" -- Kansas, US
isUSCA "620" = Just $ Left "US" -- Kansas, US
isUSCA "785" = Just $ Left "US" -- Kansas, US
isUSCA "913" = Just $ Left "US" -- Kansas, US
isUSCA "270" = Just $ Left "US" -- Kentucky, US
isUSCA "364" = Just $ Left "US" -- Kentucky, US
isUSCA "502" = Just $ Left "US" -- Kentucky, US
isUSCA "606" = Just $ Left "US" -- Kentucky, US
isUSCA "859" = Just $ Left "US" -- Kentucky, US
isUSCA "225" = Just $ Left "US" -- Lousiana, US
isUSCA "318" = Just $ Left "US" -- Lousiana, US
isUSCA "337" = Just $ Left "US" -- Lousiana, US
isUSCA "504" = Just $ Left "US" -- Lousiana, US
isUSCA "985" = Just $ Left "US" -- Lousiana, US
isUSCA "207" = Just $ Left "US" -- Maine, US
isUSCA "227" = Just $ Left "US" -- Maryland, US
isUSCA "240" = Just $ Left "US" -- Maryland, US
isUSCA "301" = Just $ Left "US" -- Maryland, US
isUSCA "410" = Just $ Left "US" -- Maryland, US
isUSCA "443" = Just $ Left "US" -- Maryland, US
isUSCA "667" = Just $ Left "US" -- Maryland, US
isUSCA "339" = Just $ Left "US" -- Massachusetts, US
isUSCA "351" = Just $ Left "US" -- Massachusetts, US
isUSCA "413" = Just $ Left "US" -- Massachusetts, US
isUSCA "508" = Just $ Left "US" -- Massachusetts, US
isUSCA "617" = Just $ Left "US" -- Massachusetts, US
isUSCA "774" = Just $ Left "US" -- Massachusetts, US
isUSCA "781" = Just $ Left "US" -- Massachusetts, US
isUSCA "857" = Just $ Left "US" -- Massachusetts, US
isUSCA "978" = Just $ Left "US" -- Massachusetts, US
isUSCA "231" = Just $ Left "US" -- Michigan, US
isUSCA "248" = Just $ Left "US" -- Michigan, US
isUSCA "269" = Just $ Left "US" -- Michigan, US
isUSCA "313" = Just $ Left "US" -- Michigan, US
isUSCA "517" = Just $ Left "US" -- Michigan, US
isUSCA "586" = Just $ Left "US" -- Michigan, US
isUSCA "616" = Just $ Left "US" -- Michigan, US
isUSCA "734" = Just $ Left "US" -- Michigan, US
isUSCA "810" = Just $ Left "US" -- Michigan, US
isUSCA "906" = Just $ Left "US" -- Michigan, US
isUSCA "947" = Just $ Left "US" -- Michigan, US
isUSCA "989" = Just $ Left "US" -- Michigan, US
isUSCA "218" = Just $ Left "US" -- Minnesota, US
isUSCA "320" = Just $ Left "US" -- Minnesota, US
isUSCA "507" = Just $ Left "US" -- Minnesota, US
isUSCA "612" = Just $ Left "US" -- Minnesota, US
isUSCA "651" = Just $ Left "US" -- Minnesota, US
isUSCA "763" = Just $ Left "US" -- Minnesota, US
isUSCA "952" = Just $ Left "US" -- Minnesota, US
isUSCA "228" = Just $ Left "US" -- Mississippi, US
isUSCA "601" = Just $ Left "US" -- Mississippi, US
isUSCA "662" = Just $ Left "US" -- Mississippi, US
isUSCA "769" = Just $ Left "US" -- Mississippi, US
isUSCA "314" = Just $ Left "US" -- Missouri, US
isUSCA "417" = Just $ Left "US" -- Missouri, US
isUSCA "573" = Just $ Left "US" -- Missouri, US
isUSCA "636" = Just $ Left "US" -- Missouri, US
isUSCA "660" = Just $ Left "US" -- Missouri, US
isUSCA "816" = Just $ Left "US" -- Missouri, US
isUSCA "406" = Just $ Left "US" -- Montana, US
isUSCA "308" = Just $ Left "US" -- Nebraska, US
isUSCA "402" = Just $ Left "US" -- Nebraska, US
isUSCA "531" = Just $ Left "US" -- Nebraska, US
isUSCA "702" = Just $ Left "US" -- Nevada, US
isUSCA "725" = Just $ Left "US" -- Nevada, US
isUSCA "775" = Just $ Left "US" -- Nevada, US
isUSCA "603" = Just $ Left "US" -- New Hampshire, US
isUSCA "201" = Just $ Left "US" -- New Jersey, US
isUSCA "551" = Just $ Left "US" -- New Jersey, US
isUSCA "609" = Just $ Left "US" -- New Jersey, US
isUSCA "640" = Just $ Left "US" -- New Jersey, US
isUSCA "732" = Just $ Left "US" -- New Jersey, US
isUSCA "848" = Just $ Left "US" -- New Jersey, US
isUSCA "856" = Just $ Left "US" -- New Jersey, US
isUSCA "862" = Just $ Left "US" -- New Jersey, US
isUSCA "908" = Just $ Left "US" -- New Jersey, US
isUSCA "973" = Just $ Left "US" -- New Jersey, US
isUSCA "505" = Just $ Left "US" -- New Mexico, US
isUSCA "575" = Just $ Left "US" -- New Mexico, US
isUSCA "212" = Just $ Left "US" -- New York, US
isUSCA "315" = Just $ Left "US" -- New York, US
isUSCA "332" = Just $ Left "US" -- New York, US
isUSCA "347" = Just $ Left "US" -- New York, US
isUSCA "516" = Just $ Left "US" -- New York, US
isUSCA "518" = Just $ Left "US" -- New York, US
isUSCA "585" = Just $ Left "US" -- New York, US
isUSCA "607" = Just $ Left "US" -- New York, US
isUSCA "631" = Just $ Left "US" -- New York, US
isUSCA "646" = Just $ Left "US" -- New York, US
isUSCA "680" = Just $ Left "US" -- New York, US
isUSCA "716" = Just $ Left "US" -- New York, US
isUSCA "718" = Just $ Left "US" -- New York, US
isUSCA "838" = Just $ Left "US" -- New York, US
isUSCA "845" = Just $ Left "US" -- New York, US
isUSCA "914" = Just $ Left "US" -- New York, US
isUSCA "917" = Just $ Left "US" -- New York, US
isUSCA "929" = Just $ Left "US" -- New York, US
isUSCA "934" = Just $ Left "US" -- New York, US
isUSCA "252" = Just $ Left "US" -- North Carolina, US
isUSCA "336" = Just $ Left "US" -- North Carolina, US
isUSCA "704" = Just $ Left "US" -- North Carolina, US
isUSCA "743" = Just $ Left "US" -- North Carolina, US
isUSCA "828" = Just $ Left "US" -- North Carolina, US
isUSCA "910" = Just $ Left "US" -- North Carolina, US
isUSCA "919" = Just $ Left "US" -- North Carolina, US
isUSCA "980" = Just $ Left "US" -- North Carolina, US
isUSCA "984" = Just $ Left "US" -- North Carolina, US
isUSCA "701" = Just $ Left "US" -- North Dakota, US
isUSCA "216" = Just $ Left "US" -- Ohio, US
isUSCA "220" = Just $ Left "US" -- Ohio, US
isUSCA "234" = Just $ Left "US" -- Ohio, US
isUSCA "326" = Just $ Left "US" -- Ohio, US
isUSCA "330" = Just $ Left "US" -- Ohio, US
isUSCA "380" = Just $ Left "US" -- Ohio, US
isUSCA "419" = Just $ Left "US" -- Ohio, US
isUSCA "440" = Just $ Left "US" -- Ohio, US
isUSCA "513" = Just $ Left "US" -- Ohio, US
isUSCA "567" = Just $ Left "US" -- Ohio, US
isUSCA "614" = Just $ Left "US" -- Ohio, US
isUSCA "740" = Just $ Left "US" -- Ohio, US
isUSCA "937" = Just $ Left "US" -- Ohio, US
isUSCA "405" = Just $ Left "US" -- Oklahoma, US
isUSCA "539" = Just $ Left "US" -- Oklahoma, US
isUSCA "580" = Just $ Left "US" -- Oklahoma, US
isUSCA "918" = Just $ Left "US" -- Oklahoma, US
isUSCA "458" = Just $ Left "US" -- Oregon, US
isUSCA "503" = Just $ Left "US" -- Oregon, US
isUSCA "541" = Just $ Left "US" -- Oregon, US
isUSCA "971" = Just $ Left "US" -- Oregon, US
isUSCA "215" = Just $ Left "US" -- Pennsylvania, US
isUSCA "223" = Just $ Left "US" -- Pennsylvania, US
isUSCA "267" = Just $ Left "US" -- Pennsylvania, US
isUSCA "272" = Just $ Left "US" -- Pennsylvania, US
isUSCA "412" = Just $ Left "US" -- Pennsylvania, US
isUSCA "445" = Just $ Left "US" -- Pennsylvania, US
isUSCA "484" = Just $ Left "US" -- Pennsylvania, US
isUSCA "570" = Just $ Left "US" -- Pennsylvania, US
isUSCA "610" = Just $ Left "US" -- Pennsylvania, US
isUSCA "717" = Just $ Left "US" -- Pennsylvania, US
isUSCA "724" = Just $ Left "US" -- Pennsylvania, US
isUSCA "814" = Just $ Left "US" -- Pennsylvania, US
isUSCA "878" = Just $ Left "US" -- Pennsylvania, US
isUSCA "401" = Just $ Left "US" -- Rhode Island
isUSCA "803" = Just $ Left "US" -- South Carolina, US
isUSCA "843" = Just $ Left "US" -- South Carolina, US
isUSCA "854" = Just $ Left "US" -- South Carolina, US
isUSCA "864" = Just $ Left "US" -- South Carolina, US
isUSCA "605" = Just $ Left "US" -- South Dakota, US
isUSCA "423" = Just $ Left "US" -- Tennessee, US
isUSCA "615" = Just $ Left "US" -- Tennessee, US
isUSCA "629" = Just $ Left "US" -- Tennessee, US
isUSCA "731" = Just $ Left "US" -- Tennessee, US
isUSCA "865" = Just $ Left "US" -- Tennessee, US
isUSCA "901" = Just $ Left "US" -- Tennessee, US
isUSCA "931" = Just $ Left "US" -- Tennessee, US
isUSCA "210" = Just $ Left "US" -- Texas, US
isUSCA "214" = Just $ Left "US" -- Texas, US
isUSCA "254" = Just $ Left "US" -- Texas, US
isUSCA "281" = Just $ Left "US" -- Texas, US
isUSCA "325" = Just $ Left "US" -- Texas, US
isUSCA "346" = Just $ Left "US" -- Texas, US
isUSCA "361" = Just $ Left "US" -- Texas, US
isUSCA "409" = Just $ Left "US" -- Texas, US
isUSCA "430" = Just $ Left "US" -- Texas, US
isUSCA "432" = Just $ Left "US" -- Texas, US
isUSCA "469" = Just $ Left "US" -- Texas, US
isUSCA "512" = Just $ Left "US" -- Texas, US
isUSCA "682" = Just $ Left "US" -- Texas, US
isUSCA "713" = Just $ Left "US" -- Texas, US
isUSCA "726" = Just $ Left "US" -- Texas, US
isUSCA "737" = Just $ Left "US" -- Texas, US
isUSCA "806" = Just $ Left "US" -- Texas, US
isUSCA "817" = Just $ Left "US" -- Texas, US
isUSCA "830" = Just $ Left "US" -- Texas, US
isUSCA "832" = Just $ Left "US" -- Texas, US
isUSCA "903" = Just $ Left "US" -- Texas, US
isUSCA "915" = Just $ Left "US" -- Texas, US
isUSCA "936" = Just $ Left "US" -- Texas, US
isUSCA "940" = Just $ Left "US" -- Texas, US
isUSCA "956" = Just $ Left "US" -- Texas, US
isUSCA "972" = Just $ Left "US" -- Texas, US
isUSCA "979" = Just $ Left "US" -- Texas, US
isUSCA "385" = Just $ Left "US" -- Utah, US
isUSCA "435" = Just $ Left "US" -- Utah, US
isUSCA "801" = Just $ Left "US" -- Utah, US
isUSCA "802" = Just $ Left "US" -- Vermont, US
isUSCA "276" = Just $ Left "US" -- Virginia, US
isUSCA "434" = Just $ Left "US" -- Virginia, US
isUSCA "540" = Just $ Left "US" -- Virginia, US
isUSCA "571" = Just $ Left "US" -- Virginia, US
isUSCA "703" = Just $ Left "US" -- Virginia, US
isUSCA "757" = Just $ Left "US" -- Virginia, US
isUSCA "804" = Just $ Left "US" -- Virginia, US
isUSCA "206" = Just $ Left "US" -- Washington, US
isUSCA "253" = Just $ Left "US" -- Washington, US
isUSCA "360" = Just $ Left "US" -- Washington, US
isUSCA "425" = Just $ Left "US" -- Washington, US
isUSCA "509" = Just $ Left "US" -- Washington, US
isUSCA "564" = Just $ Left "US" -- Washington, US
isUSCA "304" = Just $ Left "US" -- West Virginia, US
isUSCA "681" = Just $ Left "US" -- West Virginia, US
isUSCA "262" = Just $ Left "US" -- Wisconsin, US
isUSCA "274" = Just $ Left "US" -- Wisconsin, US
isUSCA "414" = Just $ Left "US" -- Wisconsin, US
isUSCA "534" = Just $ Left "US" -- Wisconsin, US
isUSCA "608" = Just $ Left "US" -- Wisconsin, US
isUSCA "715" = Just $ Left "US" -- Wisconsin, US
isUSCA "920" = Just $ Left "US" -- Wisconsin, US
isUSCA "307" = Just $ Left "US" -- Wyoming, US
isUSCA "368" = Just $ Left "CA" -- Alberta, CA
isUSCA "403" = Just $ Left "CA" -- Alberta, CA
isUSCA "587" = Just $ Left "CA" -- Alberta, CA
isUSCA "780" = Just $ Left "CA" -- Alberta, CA
isUSCA "825" = Just $ Left "CA" -- Alberta, CA
isUSCA "236" = Just $ Left "CA" -- British Columbia, CA
-- +1 250 is used in Hyder, Alaska, US, but by more people in British Columbia
-- so, 250 is treated as Canada. https://en.wikipedia.org/wiki/Area_code_250
isUSCA "250" = Just $ Left "CA" -- British Columbia, CA (also used in Hyder, Alaska)
isUSCA "604" = Just $ Left "CA" -- British Columbia, CA
isUSCA "672" = Just $ Left "CA" -- British Columbia, CA
isUSCA "778" = Just $ Left "CA" -- British Columbia, CA
isUSCA "204" = Just $ Left "CA" -- Manitoba, CA
isUSCA "431" = Just $ Left "CA" -- Manitoba, CA
isUSCA "584" = Just $ Left "CA" -- Manitoba, CA
isUSCA "428" = Just $ Left "CA" -- New Brunswick, CA
isUSCA "506" = Just $ Left "CA" -- New Brunswick, CA
isUSCA "709" = Just $ Left "CA" -- Newfoundland and Labrador, CA
isUSCA "879" = Just $ Left "CA" -- Newfoundland and Labrador, CA
isUSCA "226" = Just $ Left "CA" -- Ontario, CA
isUSCA "249" = Just $ Left "CA" -- Ontario, CA
isUSCA "289" = Just $ Left "CA" -- Ontario, CA
isUSCA "343" = Just $ Left "CA" -- Ontario, CA
isUSCA "365" = Just $ Left "CA" -- Ontario, CA
isUSCA "382" = Just $ Left "CA" -- Ontario, CA
isUSCA "387" = Just $ Left "CA" -- Ontario, CA
isUSCA "416" = Just $ Left "CA" -- Ontario, CA
isUSCA "437" = Just $ Left "CA" -- Ontario, CA
isUSCA "519" = Just $ Left "CA" -- Ontario, CA
isUSCA "548" = Just $ Left "CA" -- Ontario, CA
isUSCA "613" = Just $ Left "CA" -- Ontario, CA
isUSCA "647" = Just $ Left "CA" -- Ontario, CA
isUSCA "683" = Just $ Left "CA" -- Ontario, CA
isUSCA "705" = Just $ Left "CA" -- Ontario, CA
isUSCA "742" = Just $ Left "CA" -- Ontario, CA
isUSCA "753" = Just $ Left "CA" -- Ontario, CA
isUSCA "807" = Just $ Left "CA" -- Ontario, CA
isUSCA "905" = Just $ Left "CA" -- Ontario, CA
isUSCA "942" = Just $ Left "CA" -- Ontario, CA
isUSCA "263" = Just $ Left "CA" -- Quebec, CA
isUSCA "354" = Just $ Left "CA" -- Quebec, CA
isUSCA "367" = Just $ Left "CA" -- Quebec, CA
isUSCA "418" = Just $ Left "CA" -- Quebec, CA
isUSCA "438" = Just $ Left "CA" -- Quebec, CA
isUSCA "450" = Just $ Left "CA" -- Quebec, CA
isUSCA "468" = Just $ Left "CA" -- Quebec, CA
isUSCA "514" = Just $ Left "CA" -- Quebec, CA
isUSCA "579" = Just $ Left "CA" -- Quebec, CA
isUSCA "581" = Just $ Left "CA" -- Quebec, CA
isUSCA "819" = Just $ Left "CA" -- Quebec, CA
isUSCA "873" = Just $ Left "CA" -- Quebec, CA
isUSCA "306" = Just $ Left "CA" -- Saskatchewan, CA
isUSCA "474" = Just $ Left "CA" -- Saskatchewan, CA
isUSCA "639" = Just $ Left "CA" -- Saskatchewan, CA
isUSCA "782" = Just $ Left "CA" -- Nova Scotia, CA; Prince Edward Island, CA
isUSCA "867" = Just $ Left "CA" -- Alberta, CA; British Columbia, CA; Northwest Territories, CA; Nunavut, CA; Yukon, CA
isUSCA "902" = Just $ Left "CA" -- Nova Scotia, CA; Prince Edward Island, CA
isUSCA "800" = Just $ Right TollFree
isUSCA "900" = Just $ Right PremiumRate
isUSCA _     = Nothing -- Alright, we're done -- time to give up.

isUSCA_ :: String -> Maybe (Prefix, Either Country Purpose)
isUSCA_ s = do
  let x = isUSCA $ take 3 $ drop 2 s
  if isNothing x then Nothing else Just (1, fromJust x)

